name: CI

on:
  push:
    branches: [paper]
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: julia-actions/setup-julia@19bd4db8c427e07d56602f1c432e1a26a55d6735 # v1.8.1
        with:
          version: 1.7.3
          arch: x64
      - uses: julia-actions/cache@936559d9c8a8452e3426f2c76b596b5cdf10f442 # v1.1.3
      - uses: julia-actions/julia-buildpkg@f995fa4149fed4a8e9b95ba82f54cc107c1d832a # v1.2.0
      - uses: julia-actions/julia-runtest@7ea3b3e0bd2f7de6d8104e238f69a715c988a5d1 # v1.8.0
      - uses: julia-actions/julia-processcoverage@52227d027819970b4085fb0ac8e73d06fc16c53b # v1.2.0
      - uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # v3.1.0
        with:
          files: lcov.info
      - uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057 # v1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
