name: Compile paper

on:
  push:
    branches: [paper]
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  compile:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: xu-cheng/latex-action@2031f1a94940bfe35904fc1782bf18a9bdafc127 # v2.5.0
        with:
          root_file: paper/paper.tex
          work_in_root_file_dir: true
          post_compile: "cd paper && latexmk -c"
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: paper
          path: paper/paper.pdf
